Repository AY1920S1-CS2103T-F12-2/main, pull requests merged in 2019-10, with the labels that each got.

#23 docs: update UG, DG, Project Website
  README.adoc
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui(old).png
  docs/images/Ui.png
  docs/images/ayushC.jpg
  docs/images/damithc.jpg
  docs/images/gabrielC.jpg
  docs/images/gabrielO.jpg
  docs/images/jasonC.png
  docs/images/jerroldT.png
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/shiqiaoZ.png
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
Labels: v1.1

#26 docs: update README.adoc and repo branding
  README.adoc
  build.gradle
  docs/images/icons/Logo.png
  docs/images/icons/LogoBG.png
  docs/images/icons/LogoInvert.png
  docs/images/icons/LogoInvertBG.png
  docs/images/icons/LogoTitle.png
  docs/images/icons/LogoTitleBG.png
  gradle/wrapper/gradle-wrapper.properties
Labels: documentation

#28 Quick Fix on README link
  README.adoc
Labels: bug

#31 feat: reminder command 1.2-alpha
  src/main/java/seedu/address/logic/commands/ReminderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ReminderCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Reminder.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: v1.2

#41 feat: add `profile [INDEX]` command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ProfileCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ProfileCommandParser.java
Labels: v1.2

#43 Updated Ui elements
  docs/images/Ui.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: v1.2

#50 Commands are now non-case sensitive
  src/main/java/seedu/address/logic/commands/AddVisitCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVisitCommand.java
  src/main/java/seedu/address/logic/commands/SaveVisitCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteVisitCommandTest.java
  src/test/java/seedu/address/logic/commands/SaveVisitCommandTest.java
Labels: type.Task, v1.2

#53 feat: implement patient profile panel to show during `profile [INDEX]` command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ProfileCommand.java
  src/main/java/seedu/address/logic/parser/AddVisitCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProfilePanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ProfilePanel.fxml
  src/main/resources/view/VisitRecordForm.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: v1.2

#54 fix: addvisit command now correctly handles invalid inputs #52
  src/main/java/seedu/address/logic/parser/AddVisitCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/VisitReport.java
Labels: type.Bug, v1.2

#56 feat: test: add unalias command and tests
  src/main/java/seedu/address/logic/commands/AliasCommand.java
  src/main/java/seedu/address/logic/commands/UnaliasCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/UnaliasCommandParser.java
  src/main/java/seedu/address/model/AliasTable.java
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/logic/commands/UnaliasCommandTest.java
Labels: priority.Medium, type.Enhancement, v1.2

#71 feat: EditVisitCommand function implemented
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditVisitCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SaveVisitCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditVisitCommandParser.java
  src/main/java/seedu/address/model/person/VisitList.java
  src/main/java/seedu/address/model/person/VisitReport.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VisitListPanel.java
  src/main/java/seedu/address/ui/VisitRecordWindow.java
  src/main/resources/view/VisitListPanel.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteVisitCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/SaveVisitCommandTest.java
Labels: v1.3

#72 docs: update UG to reflect changes in v1.2
  docs/UserGuide.adoc
Labels: documentation

#75 docs: updated dev guide
  docs/DeveloperGuide.adoc
  docs/diagrams/AddVisit0.puml
  docs/diagrams/DeleteVisit0.puml
  docs/diagrams/EditVisit0.puml
  docs/images/AddVisit0.png
  docs/images/DeleteVisit0.png
  docs/images/EditVisit0.png
Labels: documentation

#76 docs: clean-up docs for documentation integrity
  docs/DevOps.adoc
  docs/DeveloperGuide.adoc
  docs/Documentation.adoc
  docs/SettingUp.adoc
  docs/Testing.adoc
  docs/UsingAppVeyor.adoc
  docs/UsingCheckstyle.adoc
  docs/UsingCoveralls.adoc
  docs/UsingTravis.adoc
Labels: documentation

#77 fixed heading
  docs/DeveloperGuide.adoc
Labels: documentation

#80 Update UG/DG, refactor unalias
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddAliasSequenceDiagram.puml
  docs/diagrams/ApplyAliasActivityDiagram.puml
  docs/diagrams/ApplyAliasSequenceDiagram.puml
  docs/images/AddAliasSequenceDiagram.png
  docs/images/ApplyAliasActivityDiagram.png
  docs/images/ApplyAliasSequenceDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AliasCommand.java
  src/main/java/seedu/address/logic/commands/UnaliasCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/UnaliasCommandParser.java
  src/main/java/seedu/address/model/AliasTable.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/logic/commands/UnaliasCommandTest.java
Labels: documentation

#78 Updated DevGuide for UI redesign (part 1)
  docs/DeveloperGuide.adoc
  docs/diagrams/UiRedesignClassDiagram.puml
  docs/images/UiRedesignClassDiagram.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProfileWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProfileWindow.fxml
Labels: documentation

#89 Docs and bug fixes
  docs/DeveloperGuide.adoc
  docs/diagrams/EditVisit1.puml
  docs/diagrams/VisitClass0.puml
  docs/images/EditVisit1.png
  docs/images/VisitClass0.png
  src/main/java/seedu/address/logic/commands/AddVisitCommand.java
  src/main/java/seedu/address/logic/commands/EditVisitCommand.java
  src/main/java/seedu/address/logic/commands/SaveVisitCommand.java
  src/main/java/seedu/address/logic/parser/EditVisitCommandParser.java
  src/main/java/seedu/address/model/person/VisitList.java
  src/main/java/seedu/address/model/person/VisitReport.java
  src/main/java/seedu/address/storage/JsonAdaptedVisit.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VisitRecordWindow.java
Labels: documentation, type.Bug, v1.3

#92 feat: add command to show all existing aliases
  src/main/java/seedu/address/logic/commands/AliasListCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AliasTable.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/AliasListWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AliasListWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/logic/commands/UnaliasCommandTest.java
Labels: type.Enhancement, v1.3

#95 UG and UI update
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/DeleteVisitCommand.java
  src/main/java/seedu/address/logic/commands/EditVisitCommand.java
  src/main/java/seedu/address/model/person/VisitList.java
  src/main/java/seedu/address/ui/EmptyVisitList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VisitCard.java
  src/main/java/seedu/address/ui/VisitListPanel.java
  src/main/java/seedu/address/ui/VisitRecordWindow.java
  src/main/resources/view/EmptyVisitListWindow.fxml
Labels: documentation, v1.3

#102 feat: add functionality to export `profile` as .txt file, `profile` reflects `visitList`
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/Profile0.puml
  docs/diagrams/Profile1.puml
  docs/diagrams/ProfileSequenceDiagram1.puml
  docs/images/Profile0.png
  docs/images/Profile1.png
  docs/images/ProfileSequenceDiagram1.png
  src/main/java/seedu/address/logic/commands/GenerateProfileCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProfileWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ProfileWindow.fxml
Labels: documentation, priority.High, type.Enhancement

#112 docs: update activity diagram
  docs/diagrams/ApplyAliasActivityDiagram.puml
  docs/images/ApplyAliasActivityDiagram.png
Labels: documentation
