Repository AY1920S1-CS2103T-F12-2/main, pull requests merged in 2019-11, with the labels that each got.

#148 fix: #122 #123 #138 #140 #142
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVisitCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VisitRecordWindow.java
Labels: type.Bug

#183 fix: #141 #152 #153 #154
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: severity.High, type.Bug

#186 fix: fix #126, #146, #147 and #159
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/AliasTable.java
  src/main/resources/view/AliasListWindow.fxml
  src/test/java/seedu/address/logic/commands/AliasListCommandTest.java
Labels: documentation, type.Bug

#193 fix: fix aliases not being case insensitive
  src/main/java/seedu/address/logic/commands/AliasCommand.java
  src/main/java/seedu/address/logic/commands/UnaliasCommand.java
  src/main/java/seedu/address/model/AliasTable.java
  src/test/java/seedu/address/logic/commands/AliasCommandIntegrationTest.java
Labels: severity.Low

#197 fix: #127, #175, #176
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/Profile0.puml
  docs/diagrams/ProfileSequenceDiagram1.puml
  docs/team/SQwQ.adoc
  src/main/java/seedu/address/logic/commands/AddVisitCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/SaveVisitCommand.java
  src/main/java/seedu/address/model/person/VisitReport.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VisitListPanel.java
  src/main/java/seedu/address/ui/VisitRecordWindow.java
  src/main/resources/view/ProfileVisitCard.fxml
  src/main/resources/view/ProfileWindow.fxml
  src/test/java/seedu/address/logic/commands/DeleteVisitCommandTest.java
  src/test/java/seedu/address/logic/commands/EditVisitCommandTest.java
  src/test/java/seedu/address/logic/commands/SaveVisitCommandTest.java
Labels: documentation, type.Bug

#201 chore: changed PPP name
  docs/team/sqwq.adoc
Labels: documentation

#205 PPP submission
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/images/UiConcept1.png
  docs/images/UiConcept2.png
  docs/images/UiConcept3.png
  docs/images/UiConcept4.png
  docs/images/UiConceptFinal.png
  docs/team/gachia.adoc
Labels: documentation

#206 docs: multiple changes
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/stylesheets/asciidoctor.css
  docs/team/reignofcomputer.adoc
  docs/templates/_header.html.slim
Labels: documentation

#209 Refactor
  docs/UserGuide.adoc
  src/main/java/unrealunity/visit/logic/commands/DeleteVisitCommand.java
  src/main/java/unrealunity/visit/logic/commands/EditVisitCommand.java
  src/main/java/unrealunity/visit/logic/parser/DeleteVisitCommandParser.java
  src/main/java/unrealunity/visit/logic/parser/EditVisitCommandParser.java
  src/main/java/unrealunity/visit/logic/parser/ParserUtil.java
Labels: type.Bug

#210 docs: update UG and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UGAddAlias.png
  docs/images/UGAliasList.png
  docs/images/UGApplyAlias.png
  docs/images/UGUnalias.png
  docs/team/wingedevil.adoc
  docs/team/wingedevil.pdf
  src/main/java/unrealunity/visit/model/AliasTable.java
  src/main/java/unrealunity/visit/ui/AliasListWindow.java
  src/test/java/unrealunity/visit/logic/commands/AliasCommandIntegrationTest.java
Labels: documentation, type.Bug

#212 docs: add PPP, update UG and DG
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/Profile1.puml
  docs/diagrams/ProfileSequenceDiagram2.puml
  docs/images/PppProfile0.png
  docs/images/Profile1.png
  docs/images/ProfileSequenceDiagram2.png
  docs/team/q-gabe.adoc
Labels: documentation

#213 fix: adjust PPP for page limit
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/q-gabe.adoc
  docs/team/wingedevil.pdf
Labels: documentation
